# Generated by Django 5.2.4 on 2025-08-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categoty',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='particpants',
            new_name='participants',
        ),
    ]
