# Generated by Django 5.2.4 on 2025-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_categoty_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.CharField(choices=[('RAJSHAHI', 'Rajshahi'), ('DHAKA', 'Dhaka'), ('KHULNA', 'Khulna'), ('CUMILLA', 'Cumilla'), ('CHITTAGONG', 'Chittagong'), ('MYMENSHINGH', 'Mymenshingh'), ('RANGPUR', 'Rangpur'), ('SYLLET', 'Syllet')], default='RAJSHAHI'),
        ),
    ]
