# Generated by Django 5.2.4 on 2025-09-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
